#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"
#include <wx/filedlg.h>
//// end generated include

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
protected:
	// Handlers for MyFrame1 events.
	void load_imageOnButtonClick(wxCommandEvent& event);
	void load_maskOnButtonClick(wxCommandEvent& event);
	void save_imageOnButtonClick(wxCommandEvent& event);
	void mask_optionsOnRadioBox(wxCommandEvent& event);
	void colorButtonOnButtonClick(wxCommandEvent& event);
	void Form_Resize(wxSizeEvent & e);
	void Repaint();
	void set_mask();
public:
	/** Constructor */
	GUIMyFrame1(wxWindow* parent);
	//// end generated class members

	wxBitmap bitmap_image;	//zmienna przechowujaca obrazek tla
	wxBitmap bitmap_mask; // zmienna przechowujaca obrazek maski
	wxImage img_org; //zapisujemy tu wczytana bitmape
	wxImage img_cpy; //dokonujemy zmian na tej kopii obrazka
	wxImage img_mask; //zapisujemy tu wczytana maske
	int mask_choice; // pomocniczy int do wyboru sposobu kombinacji obrazka z maska (0, 1 lub 2)
	wxColor color_choice; // pomocnicza zmienna wybranego koloru w masce (R lub G lub B lub Z)
};

#endif // __GUIMyFrame1__