#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void load_imageOnButtonClick( wxCommandEvent& event );
		void load_maskOnButtonClick( wxCommandEvent& event );
		void save_imageOnButtonClick( wxCommandEvent& event );
		void mask_optionsOnRadioBox( wxCommandEvent& event );
		void color_optionsOnRadioBox( wxCommandEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members

};

#endif // __GUIMyFrame1__
